### ISSUE TITLE
Video is off center in firefox 45.8.0 ESR

### ISSUE THREAD

**Issue by rangeroob** [poeti8/findrap.xyz#4]
here is a screenshot: http://imgur.com/a/ZQeQO

**Comment by poeti8** [comment]
Which version of Firefox?

**Comment by rangeroob** [comment]
Firefox version 45.8 extended support release

**Comment by rangeroob** [comment]
https://en.m.wikipedia.org/wiki/Template:Firefox_usage_share

I just checked the usage share of the browser against all versions of Firefox and total usage. And I think it might not be worth the effort so I'll close the issue
